name: TryTpa
version: 2.0
api-version: 1.19
folia-supported: true
main: net.nightvanilla.tpa.TryTpa
author: VertrauterDavid
website: https://vertrauterdavid.net/ & https://github.com/vertrauterdavid/

commands:
  removetpaall:
  tpa:
  tpaccept:
  tpaaccept:
  tpahere:
  tpahereaccept:
  tpaall:
  tpatoggle:
  tpaheretoggle:
  tpaalltoggle:
